### PR TITLE
Map attributes

### PR DESCRIPTION
**Pull request by mikesplain**
Add the ability to map attributes the way we already can for `map_state`.  This works well for things like media players where you may want to look up attribute values and map it to ui values.  

Fixes https://github.com/nervetattoo/banner-card/issues/109

### CODE REVIEW

**Comment by nervetattoo** [comment]
Awesome, thanks!
Only problem is that the latest version of the code resides in the `beta` branch and has been ported to Typescript and re-organized. Do you want to re-apply the fix towards the beta branch? If not I can manually merge it and port it when I find the time, making sure that I attribute the commit to you.

**Comment by mikesplain** [comment]
Thanks @nervetattoo! Rebased and retargeted to the beta branch, thanks for the clean migration to TS, super easy rebase.  Let me know if you need anything else from me!

**Comment by nervetattoo** [comment]
Looked clean and nice. Thanks for the addition, it makes super sense so 👍

**Comment by mikesplain** [comment]
Awesome thanks! I have some more code that I’ll rework and contribute soon too. Thanks for the great plugin!

**Pull request merged**
