### PR TITLE
fix for covers

### PR DESCRIPTION
**Pull request by fastcolors**
..fingers crossed :-)

### CODE REVIEW

**Comment by fastcolors** [comment]
didn't work in checking opening closing of entities without current_position attire... let me test some more.

**Comment by nervetattoo** [comment]
Let me know when you've tested some more. The initial version of the PR looked good so when you have it working and modified the code to that I'll merge it and cut a new release with it.

**Comment by fastcolors** [comment]
turns out all the fixes were good to go... but update to  101.2  somehow broken cover.state update  and got fixed when I updated to 101.3.

anyhow this works.

**Comment by soloam** [comment]
The fix still does not work.. I can get it up if the window is fully closed, or down if fully open, but if window is somewhere in between 0% and 100% it keeps the inverse arrow grayed out. 

Fully Closed (OK)
image
image

Fully Open (OK)
image

image

Half Way Open (NOK)

image

image

**Pull request merged**
